# Generated by Django 5.2.6 on 2025-09-26 09:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_name', models.CharField(max_length=100)),
                ('agent_short_desc', models.CharField(max_length=255)),
                ('agent_long_desc', models.TextField(blank=True)),
                ('problem', models.TextField(blank=True)),
                ('solution', models.TextField(blank=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('agent_configuration', models.JSONField(blank=True, null=True)),
                ('agent_type', models.CharField(choices=[('BOT', 'Bot'), ('SITE', 'Site')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentAgent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.agent')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.department')),
            ],
            options={
                'unique_together': {('department', 'agent')},
            },
        ),
    ]
