# Generated by Django 5.2.6 on 2025-10-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='agent_logos/'),
        ),
        migrations.AddField(
            model_name='department',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='department_logos/'),
        ),
    ]
