# Generated by Django 5.2.6 on 2025-10-07 10:35

import myapp.models.agent
import myapp.models.department
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_agent_logo_department_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='agent_logos/', validators=[myapp.models.agent.validate_logo_file]),
        ),
        migrations.AlterField(
            model_name='department',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='department_logos/', validators=[myapp.models.department.validate_logo_file]),
        ),
    ]
